FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy dependencies to app
COPY package*.json .
COPY tsconfig.json .
COPY tsconfig.node.json .

# Install dependencies
RUN npm install

COPY . .

# exposing port
EXPOSE 5173

# running the app
CMD ["npm", "run", "dev"]